/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#171b28",
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "tertiary-fixed-dim": "#c3c6d7",
        "surface-container": "#142033",
        "primary-fixed-dim": "#00dce6",
        "outline-variant": "#3a494b",
        "background": "#071326",
        "on-tertiary-container": "#5c5f6e",
        "on-secondary-container": "#ffd2cc",
        "secondary-fixed-dim": "#ffb4aa",
        "status-error": "#ff3b30",
        "surface-container-low": "#0f1c2f",
        "on-surface": "#d7e3fd",
        "tertiary": "#f8f7ff",
        "on-surface-variant": "#b9cacb",
        "on-primary": "#00373a",
        "inverse-surface": "#d7e3fd",
        "tertiary-fixed": "#dfe1f4",
        "on-primary-container": "#006a70",
        "aurora-red": "rgba(255, 59, 48, 0.15)",
        "glass-surface": "rgba(11, 17, 37, 0.6)",
        "primary": "#e0fdff",
        "on-primary-fixed": "#002022",
        "inverse-on-surface": "#253145",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#930005",
        "on-secondary": "#690003",
        "status-success": "#00f2fe",
        "surface-tint": "#00dce6",
        "secondary-fixed": "#ffdad5",
        "inverse-primary": "#00696f",
        "surface-container-highest": "#293549",
        "outline": "#849495",
        "on-secondary-fixed": "#410001",
        "surface-dim": "#071326",
        "error-container": "#93000a",
        "aurora-cyan": "rgba(0, 242, 254, 0.15)",
        "surface-container-lowest": "#030e21",
        "tertiary-container": "#d8daec",
        "surface-bright": "#2e3a4e",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#2c303e",
        "error": "#ffb4ab",
        "primary-container": "#00f2fe",
        "on-primary-fixed-variant": "#004f53",
        "surface-container-high": "#1e2a3e",
        "on-background": "#d7e3fd",
        "secondary-container": "#c5020b",
        "secondary": "#ffb4aa",
        "on-tertiary-fixed-variant": "#434655",
        "surface-variant": "#293549",
        "primary-fixed": "#6ff6ff",
        "surface": "#071326"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "8rem",
        "container-max": "1280px",
        "grid-margin": "2rem",
        "grid-gutter": "1.5rem"
      },
      fontFamily: {
        "headline-lg": ["Sora"],
        "body-lg": ["Inter"],
        "label-code": ["JetBrains Mono"],
        "display-lg-mobile": ["Sora"],
        "display-lg": ["Sora"],
        "body-md": ["Inter"],
        "headline-md": ["Sora"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-code": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
