/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1c1917",
        "glass-border": "rgba(28, 25, 23, 0.08)",
        "tertiary-fixed-dim": "#a8a29e",
        "surface-container": "#f5f2eb",
        "primary-fixed-dim": "#e7e4dc",
        "outline-variant": "#e7e4dc",
        "background": "#faf8f5",
        "on-tertiary-container": "#57534e",
        "on-secondary-container": "#7c2d12",
        "secondary-fixed-dim": "#fdbb2d",
        "status-error": "#dc2626",
        "surface-container-low": "#faf8f5",
        "on-surface": "#1c1917",
        "tertiary": "#e7e4dc",
        "on-surface-variant": "#57534e",
        "on-primary": "#faf8f5",
        "inverse-surface": "#121110",
        "tertiary-fixed": "#e7e4dc",
        "on-primary-container": "#faf8f5",
        "aurora-red": "rgba(194, 65, 12, 0.05)",
        "glass-surface": "rgba(255, 255, 255, 0.75)",
        "primary": "#1c1917",
        "on-primary-fixed": "#121110",
        "inverse-on-surface": "#faf8f5",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#7c2d12",
        "on-secondary": "#fafaf9",
        "status-success": "#84cc16",
        "surface-tint": "#d97706",
        "secondary-fixed": "#fed7aa",
        "inverse-primary": "#d97706",
        "surface-container-highest": "#d6d1c4",
        "outline": "#78716c",
        "on-secondary-fixed": "#7c2d12",
        "surface-dim": "#f5f2eb",
        "error-container": "#fef2f2",
        "aurora-cyan": "rgba(217, 119, 6, 0.05)",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#e7e4dc",
        "surface-bright": "#ffffff",
        "on-error-container": "#991b1b",
        "on-tertiary": "#1c1917",
        "error": "#ef4444",
        "primary-container": "#d97706",
        "on-primary-fixed-variant": "#b45309",
        "surface-container-high": "#e7e4dc",
        "on-background": "#1c1917",
        "secondary-container": "#ffedd5",
        "secondary": "#c2410c",
        "on-tertiary-fixed-variant": "#57534e",
        "surface-variant": "#e7e4dc",
        "primary-fixed": "#1c1917",
        "surface": "#faf8f5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "8rem",
        "container-max": "1280px",
        "grid-margin": "2rem",
        "grid-gutter": "1.5rem"
      },
      fontFamily: {
        "headline-lg": ["Sora"],
        "body-lg": ["Inter"],
        "label-code": ["JetBrains Mono"],
        "display-lg-mobile": ["Sora"],
        "display-lg": ["Sora"],
        "body-md": ["Inter"],
        "headline-md": ["Sora"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-code": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
